### ISSUE TITLE
Cannot insert RoundPipe Element with its parent as Network Element

### ISSUE THREAD

**Issue by iboates** [gioagu/3dcitydb_ade#10]
So I am able to successfully add my network element, but then I drop down to the `component` relations and try to read them and insert them into the database while indicating their their parent element is the `Network`.  To do this, just after inserting the `Network`, I grab its returned `id` value and pass it to the function to add the `RoundPipe` element.  It fails on the first element, complaining that:

```
NOTICE:  citydb_pkg.utn9_insert_network_feature (id:44420): insert or update on table"utn9_network_feature" violates foreign key constraint "utn9_ntw_feat_utn_ntw_feat_fk1"
NOTICE:  citydb_view.utn9_insert_ntw_feat_distrib_elem_pipe_round(): control reached end of function without RETURN
ERROR:  control reached end of function without RETURN
CONTEXT:  PL/pgSQL function citydb_view.utn9_insert_ntw_feat_distrib_elem_pipe_round(integer,character varying,character varying,character varying,character varying,character varying,geometry,timestamp with time zone,timestamp with time zone,character varying,character varying,timestamp with time zone,character varying,character varying,character varying,integer,integer,character varying,character varying,character varying,date,character varying,character varying,character varying,integer,integer,geometry,character varying,numeric,numeric,character varying,numeric,character varying,numeric,character varying,numeric,character varying,character varying)
```

(above output is from PgAdmin when trying to manually insert, even when the `Network` is indeed in the database.)

Since I'm using "smart" inserts and not specifying the id explicitly, you don't see the ids.  So I rigged u pthe python script to spit out the id of the parent feature before trying the second.  This is the output before failing:
```

b"
        SELECT citydb_view.utn9_insert_network(
        id := NULL,
        gmlid := 'NetworkID_4a42ef3a-14a5-11e8-a94b-7824afca2075',
        gmlid_codespace := NULL,
        name := NULL,
        name_codespace := NULL,
        description := NULL,
        envelope := NULL,
        creation_date := NULL,
        termination_date := NULL,
        relative_to_terrain := NULL,
        relative_to_water := NULL,
        last_modification_date := NULL,
        updating_person := NULL,
        reason_for_update := NULL,
        lineage := NULL,
        network_parent_id := NULL,
        network_root_id := NULL,
        class := NULL,
        function := 'distribution',
        usage := 'distribution',
        commodity_id := NULL,
        schema_name := 'citydb');
    "
PARENT ID OF LAST INSERTED FEATURE: 44419
RELATION: component
b"
        SELECT citydb_view.utn9_insert_ntw_feat_distrib_elem_pipe_round(
        id := NULL,
        gmlid := 'RoundPipeID_4e80843c-14a5-11e8-a94b-7824afca2075',
        gmlid_codespace := NULL,
        name := NULL,
        name_codespace := NULL,
        description := NULL,
        envelope := ST_Envelope(ST_GeomFromText('LINESTRING Z (426686.205399994 5450370.83199954 112.636166102332,426683.311999993 5450370.80149954 112.26385708932)', NULL)),
        creation_date := NULL,
        termination_date := NULL,
        relative_to_terrain := NULL,
        relative_to_water := NULL,
        last_modification_date := NULL,
        updating_person := NULL,
        reason_for_update := NULL,
        lineage := NULL,
        ntw_feature_parent_id := 44419,
        ntw_feature_root_id := NULL,
        class := NULL,
        function := 'distribution',
        usage := NULL,
        year_of_construction := NULL,
        status := 'inUse',
        location_quality := NULL,
        elevation_quality := NULL,
        cityobject_id := NULL,
        prot_element_id := NULL,
        geom := ST_GeomFromText('LINESTRING Z (426686.205399994 5450370.83199954 112.636166102332,426683.311999993 5450370.80149954 112.26385708932)', NULL),
        function_of_line := NULL,
        is_gravity := NULL,
        ext_width := NULL,
        ext_width_unit := NULL,
        ext_height := NULL,
        ext_height_unit := NULL,
        ext_diameter := NULL,
        ext_diameter_unit := NULL,
        int_diameter := NULL,
        int_diameter_unit := NULL,
        schema_name := 'citydb')
    "
```

As you can see, I have specified the `RoundPipe`s `id` to be `44419`, but it still fails.  Is this not the correct way to establish the parent-child relationship between `Network` elements and their `component` children? If it is, then `"utn9_ntw_feat_utn_ntw_feat_fk1"` is the culprit somehow.

**Comment by gioagu** [comment]
It is not a bug, you are doing a conceptual mistake.

1) Check the UML diagram 

[UTN Core](https://github.com/gioagu/3dcitydb_ade/blob/master/03_utility_network_ade/diagrams/UtilityNetwork_ADE_Core_Mapping.tif)

Between network and network_feature there is a many-to-many relation. This is implemented by means of the association table utn9_network_to_network_feature.
Hence, you first enter the network, then the network_feature, and then you fill the association table.
Simplified example:

WITH n AS (
 SELECT citydb_view.utn9_insert_network(
        name:='network_1'
        ) AS ntw_id
 ),
nf AS (
 SELECT citydb_view.utn9_insert_ntw_feat_distrib_elem_pipe_round(
        name := 'ntw_feature_1',
        function := 'distribution',
        status := 'inUse'
        ) AS ntw_feat_id
 )
SELECT citydb_pkg.utn9_insert_network_to_network_feature(n.ntw_id, nf.ntw_feat_id) FROM n, nf

2) As the name says, the ntw_feature_parent_id contains the id of the parent network FEATURE! ;-)
This is implemented to allow for nested network_features (relation "consistsOf").

**Comment by gioagu** [comment]
PS. please note that there are not insert functions for the associations tables in the citydb_view package.
You can use those in the citydb_pkg schema, however.
