### ISSUE TITLE
wrong field types in citydb.utn9_medium_supply

### ISSUE THREAD

**Issue by iboates** [gioagu/3dcitydb_ade#15]
`citydb.utn9_medium_supply.cur_supply_flow_rate_unit` and `citydb.utn9_medium_supply.pot_supply_flow_rate_unit` are defined as `numeric` type. I am fairly certain they should be defined as `character varying` type.

I am finishing up for the day but I can have a look at this tomorrow if you don't have time.  I have not had a chance to test the last change (changing `cityobject_id` to `conn_cityobject_id`.

**Comment by gioagu** [comment]
Corrected
