### ISSUE TITLE
Why do all the utn9_medium_supply tables have the same schema?

### ISSUE THREAD

**Issue by iboates** [gioagu/3dcitydb_ade#16]
All of the `utn9_medium_supply_water/electrical/solid/...` tables have the same schema, I am wondering why they are not all collapsed into `utn9_medium_supply` and just have views in `citydb_view` separating them.

![image](https://user-images.githubusercontent.com/13814358/39580685-fb886062-4ee9-11e8-8ba5-4268c33e6595.png)

**Comment by gioagu** [comment]
Actually, it is right now already as you wish.
In schema citydb there is only one table, utn9_medium_supply.
I guess you took this screenshot while looking at the citydb_view schema...
