### ISSUE TITLE
Is it really necessary to have a separate insert function for all MediumSupply elements?

### ISSUE THREAD

**Issue by iboates** [gioagu/3dcitydb_ade#18]
As far as I can tell, all of the `citydb_view` functions for insertion of `MediumSupply` elements are identical. Is it necessary to have it like this? Having it like this means that I have to institute a conditional check in my script to determine if the medium supply is liquid or electrical, so that I can call up the correct query before inserting it, even though the parameter requirements are identical.

**Comment by gioagu** [comment]
The „smart“ insert function are meant to take care – among the rest – to automatically set the correct value of objectclass_id.
This is one of the reasons why they correspond to the specific classes.

If you prefer a generic insert function, you can use the one in the citydb_pkg schema (ut9_insert_medium_supply), however you must take care of providing the correct value of objectclass_id (you can look it up in the objectclass table).

**Comment by iboates** [comment]
That makes sense, thanks.
