### ISSUE TITLE
Suggestion: define all constraints as being DEFERRABLE

### ISSUE THREAD

**Issue by iboates** [gioagu/3dcitydb_ade#19]
It can be quite a headache to build an entire database from scratch, even with the smart insert functions, because you have to be extremely precise with the insert order due to the constraints. Obviously removing the constraints is not a realistic option, but they can be marked as "deferrable", meaning that, if deferred, the constraints can be ignored until the next commit, at which point there will be a bulk constraint validation.

I suggest that all the constraints be re-written as being `DEFERRABLE` to facilitate this.

Note that this does not allow violation of constraints, it just doesn't check them until a commit is made, so data can be inserted in any order as long as the final state is valid.

This capability is not used by the core 3dcitydb, and I think it would be useful there, but I am thinking that I can test it here first.

More info:

https://stackoverflow.com/questions/16323236/deferrable-check-constraint-in-postgresql

https://www.postgresql.org/docs/9.6/sql-set-constraints.html

**Comment by gioagu** [comment]
Yes, this could be worth a try, indeed!
I will consider it in the next release.
Thanks for the suggestion!
