### ISSUE TITLE
citydb_view.utn9_insert_ntw_feat_distrib_elem_pipe_round is calling functions that don't exist

### ISSUE THREAD

**Issue by iboates** [gioagu/3dcitydb_ade#2]
I am trying to do some dummy data test inserts.  I am trying to use the updatable view in the citydb_view schema, as demonstrated in the [Energy ADE test data folder](https://github.com/gioagu/3dcitydb_ade/blob/master/02_energy_ade/test_data/Energy_ADE_Insert_data_example_scripts.sql) (insert mode 4a - smart function with id but no objectclass id) .

It seems that the function `citydb_view.utn9_insert_ntw_feat_distrib_elem_pipe_round` is trying to call functions that do not exist.  With the query:

```
SELECT citydb_view.utn9_insert_ntw_feat_distrib_elem_pipe_round(
	id := 10000,
	gmlid := 'test_gmlid'
);
```

This error is returned:

```
NOTICE:  citydb_view.utn9_insert_ntw_feat_distrib_elem_pipe_round(): function citydb_pkg.utn9_insert_distribution_element(id => integer, objectclass_id => integer, function_of_line => character varying, is_gravity => numeric, ext_width => numeric, ext_width_unit => character varying, ext_heigth => numeric, ext_heigth_unit => character varying, ext_diameter => numeric, ext_diameter_unit => character varying, int_diameter => numeric, int_diameter_unit => character varying, schema_name => character varying) does not exist
ERROR:  control reached end of function without RETURN
CONTEXT:  PL/pgSQL function citydb_view.utn9_insert_ntw_feat_distrib_elem_pipe_round(integer,character varying,character varying,character varying,character varying,character varying,geometry,timestamp with time zone,timestamp with time zone,character varying,character varying,timestamp with time zone,character varying,character varying,character varying,integer,integer,character varying,character varying,character varying,date,character varying,character varying,character varying,integer,integer,geometry,character varying,numeric,numeric,character varying,numeric,character varying,numeric,character varying,numeric,character varying,character varying)
```

Indeed the function `citydb_pkg.utn9_insert_distribution_element` does not exist in citydb_pkg, it is named `citydb_pkg.utn9_insert_distrib_element`.

I tried changing `citydb_pkg.utn9_insert_distribution_element` to `citydb_pkg.utn9_insert_distrib_element` on my local installation to see if it would fix the problem, but I still get the error, saying instead that `citydb_pkg.utn9_insert_distrib_element` does not exist, which makes me think it is a parameter signature issue.  But the definition of all the input parameters have the `DEFAULT NULL` keywords in them, so I would think that the omission of any of them should not cause a problem.

**Comment by iboates** [comment]
Furthermore, there is a consistent naming error in the definition body of `citydb_view.utn9_insert_ntw_feat_distrib_elem_pipe_round` - the word `height` is misspelled as `heigth`.

**Comment by gioagu** [comment]
corrected, both spelling issues and stored procedures.
now it should work :-)
