### ISSUE TITLE
Update to UtiltiyNetwork ADE schema

### ISSUE THREAD

**Issue by iboates** [gioagu/3dcitydb_ade#21]
The UtilityNetwork ADE schema has been updated, most of the changes appear to be to the "Network Components" package.

Giorgio, did you use any kind of software to generate the database schema, or did you do all this by hand?

**Comment by gioagu** [comment]
The new UtilityNetwork ADE version should actually contain (for the major part) suggested improvements and minor bugfixes that I already implemented in the current version.
The database schema was derived manually.

As per 3DCityDB 4.0, you may want to give a try at the ADE manager plugin, which derives a database schema automatically from the xsd.
My implementation is still for version 3.3.1.
