### ISSUE TITLE
How do you establish a connection between a network feature (for example, a RoundPipe element) and its corresponding FeatureGraph element?

### ISSUE THREAD

**Issue by iboates** [gioagu/3dcitydb_ade#4]
I am now trying to batch-insert the pipes in my water network.  My `RoundPipe` features are associated with their `FeatureGraphs` by an `xlink` like so:

```
<utility:RoundPipe gml:id="RoundPipeID_46e3ae58-da83-41d6-bbf4-25001ba16bc5">
    ...
    <utility:topoGraph xlink:href="#FeatureGraphID_eba1e804-93ae-43ab-8efd-261316f1ed5b"/>
    ...
</utility:RoundPipe>
```

This was done because it was deemed logical to store the `FeatureGraph` elements as children of the `NetworkGraph` element, and the `RoundPipe` elements as children of the `Network` element.

I have a python script that is parsing the XML, so I have access to the `FeatureGraph`'s `gmlid` for every `RoundPipe`.  But I do not see a field in the `utn9_network_feature` tables that indicates the associated `FeatureGraph`.  How then, will the `RoundPipe` element "know" which `FeatureGraph` element corresponds to it?

**Comment by gioagu** [comment]
I guess what you need is to have a look at the table utn9_feature_graph. It contains a column named "ntw_feature_id", where you write the id (not the gmlid!!) of the corresponding network feature.

In other words, you need to know which id in the 3dcitydb is associated to the linked feature.
You may want to store first the network feature, get its assigned id, and pass it to the network graph feature.

I hope this could help you.

**Comment by iboates** [comment]
I can change the script to work in this way, but I am just wondering why the id (not gmlid) is used to make the association? I would suggest that if possible, the various network features have a field that can be used to indicate their associated `FeatureGraph`, as that is how it is done in the CityGML schema.  There is a relationship saying that a `FeatureGraph` belongs to a `AbstractNetworkFeature` via the 0..1 relation `+topoGraph`, but there is no relationship going in the opposite direction (something like `+isTopoGraphOf`):

![image](https://user-images.githubusercontent.com/13814358/36220992-e94bf342-11bc-11e8-975e-806f4ed29ac6.png)

**Comment by gioagu** [comment]
Hi,

the db implementation follows the same criteria of the "vanilla" 3dcitydb.
Regarding the ids instead of the gmlids, this is coherently implemented throughout the citydb. The gmlid is "just" an attribute in the citydb.
The current way of defining the "parent_id" in the feature_graph table follows the classical way of implementing (db-wise) this type of relation.
For analogy, check how a room is connected to a building in the citydb.
The same rules are used to implement the +topoGraph relation.

**Comment by iboates** [comment]
Alright, that makes sense.
